Feat/adiciona teste
grupotesseract/jornadasolar-native pull request #42
Opened 2021-12-13 14:21 UTC by Keikonichi

Acrescenta testID e accessibilityLabel aos códigos que serão testados:
- AudioPlayer 
- BotaoNovoHabito
- ButtonLink
- CardDetalheCategoria
- CardRegistroDoDia
- Categoria
- DateNavigator
- Dialogo
- EdicaoDiario
- graficos/ToggleButton
- GrupoDeHabitosCheckbox
- HabitoCheckbox
- ModalEdicao
- TextButton
- Bottontabs.routes
- ModalAceiteLgpd
- ModalMudancaLinguagem
- Novidade

Alguns foram acrescentados testID e accessibilityLabel, outros só foram acrescentados testID.

2021-12-20 21:47 UTC, ThaisMap commented
Testei esse código no Appium Inspector, verificando se cada componente tinha pegado o testID e cheguei nesse resultado:
- [ ]  Faltou o testID do input de emoji no modal de edição
- [ ]  Faltou o Accessibility Label do input de anotação
- [ ]  Faltou o Accessibility Label  dos itens na lista de meditação
- [ ]  O testID de preenche sentimentos e etc no diário, não foi reconhecido
- [ ]  Faltou colocar o testID dos itens da lista do perfil, meus dados e opções na tela de notificações
- [ ]  O toggleButton da tela de gráficos ficou com “testID”

Os seguintes são sugestões:
- [ ]  mudar o nome do botão voltar no DateNavigator pra não ficar igual ao botão voltar genérico
- [ ]  botões editar do grupo hábitos talvez precise incluir o nome do grupo
- [ ]  no textInput tem accessibilityLabel 2 vezes

2021-12-20 22:00 UTC, ThaisMap requested changes

2021-12-20 22:00 UTC, ThaisMap commented on src/components/Categoria.tsx
>        <Text>
Aqui acho que vai precisar colocar o testID e o accessibility Label nese Text e não no textButton, algo como 
`<Text testID={testID} accessibilityLabel={testID}>`

2022-01-12 15:12 UTC, evandrododo requested changes
Nenhum problema de funcionalidade, somente ajustes de tabulação, espaço e aspas, coisas que são facilmente resolvidas com "embelezadores de código".
Para ajustar o código eu recomendo extensões do vscode como o prettify e/ou o eslint, mas também podem ser feitas manualmente.

2022-01-12 15:12 UTC, evandrododo commented on src/components/BotaoNovoHabito.tsx
> +  }
remover espaço desnecessario

2022-01-12 15:12 UTC, evandrododo commented on src/components/BotaoNovoHabito.tsx
> +    onPress()
remover espaço desnecessário

2022-01-12 15:12 UTC, evandrododo commented on src/components/ButtonLink.tsx
> +      accessibilityLabel={testID}>
Quebrar as propriedades seguindo o padrão de uma por linha quando tiver mais de duas
```suggestion
      <Pressable 
        style={styles.botao}
        onPress={onPress} 
        testID={testID} 
        accessibilityLabel={testID}
      >
```

2022-01-12 15:12 UTC, evandrododo commented on src/components/CardRegistroDoDia.tsx
> +
remover linha desnecessária

2022-01-12 15:12 UTC, evandrododo commented on src/components/CardRegistroDoDia.tsx
> +            testID='preencheHabitos'
Seguir padrão de aspas duplas (" ") ao invés aspas simples (' ')  
```suggestion
            testID="preencheHabitos"
```

2022-01-12 15:12 UTC, evandrododo commented on src/components/EdicaoDiario.tsx
> +  }
remover espaços

2022-01-12 15:12 UTC, evandrododo commented on src/components/GrupoDeHabitosCheckbox.tsx
> +              onPress={handlePressHabito}
remover espaços desnecessários

2022-01-12 15:12 UTC, evandrododo commented on src/components/HabitoCheckbox.tsx
> +  }
remover espaços desnecessários

2022-01-12 15:12 UTC, evandrododo commented on src/components/HabitoCheckbox.tsx
> +  isEmEdicao = false,
remover espaços desnecessários

2022-01-12 15:12 UTC, evandrododo commented on src/components/HabitoCheckbox.tsx
> +      accessibilityLabel={"habitoLabel"+habito.nome}>
quebrar linhas

2022-01-12 15:12 UTC, evandrododo commented on src/components/ModalMudancaLinguagem.tsx
> +        <Pressable onPress={onFecha} testID='botaoFechaModal' style={styles.container}>
seguir padrão de aspas

2022-01-12 15:12 UTC, evandrododo commented on src/components/Novidade.tsx
> +  }
remover espaços desnecessários

2022-01-12 15:12 UTC, evandrododo commented on src/routes/BottomTabs.routes.tsx
> +
remover linhas desnecessaria

2022-01-24 20:28 UTC, evandrododo approved these changes

2022-01-24 20:29 UTC, merged